import '../styles/globals.css'
import { Gantari } from 'next/font/google'
import LayoutContainer from "../processes/layoutContainer/LayoutContainer";

const inter = Gantari({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} style={{marginRight: '0px !important'}}>
      <LayoutContainer>
        {children}
      </LayoutContainer>
      </body>
    </html>
  )
}
